services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - nginx-php
  php-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php-container
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php
  database:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: db_user
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - nginx-php
volumes:
  database_data:

networks:
  nginx-php: